
// Serialise all computed cover data into a Typst _data.typ file

import {pt_to_typst, in_to_pt, escape_typst_str, escape_typst_content} from './utils.js'
import type {CoverSchema} from './schema.js'
import type {PrinterDimensions} from './printers.js'
import type {ResolvedColors} from './design.js'
import type {FontSizes} from './font_sizes.js'
import type {ThemeLayout} from './themes.js'

/** Helper: emit a Typst #let binding for a length value in inches */
function len(name:string, inches:number):string {
    return `#let ${name} = ${pt_to_typst(in_to_pt(inches))}`
}

/** Helper: emit a Typst #let binding for a point value */
function ptval(name:string, pt:number):string {
    return `#let ${name} = ${pt_to_typst(pt)}`
}

/** Helper: emit a Typst #let binding for a string */
function str(name:string, value:string):string {
    return `#let ${name} = "${escape_typst_str(value)}"`
}

/** Helper: emit a Typst #let binding for a boolean */
function bool(name:string, value:boolean):string {
    return `#let ${name} = ${value ? 'true' : 'false'}`
}

/** Helper: emit a Typst #let binding for a color */
function color(name:string, hex:string):string {
    return `#let ${name} = rgb("${hex}")`
}

/** Helper: emit a Typst #let binding for a content block (allows simple markup) */
function content(name:string, value:string):string {
    return `#let ${name} = [${escape_typst_content(value)}]`
}

/**
 * Build the full _data.typ file content from all computed cover data.
 * The Typst template imports this file to receive all variables.
 */
export function build_data_file(
    schema:CoverSchema,
    dims:PrinterDimensions,
    colors:ResolvedColors,
    font_family:string,
    font_sizes:FontSizes,
    layout:ThemeLayout,
    image_filename:string | null,
    has_barcode:boolean,
):string {
    const lines:string[] = ['// Auto-generated by paper_cover generator — do not edit', '']

    // Canvas dimensions
    lines.push('// Canvas dimensions')
    lines.push(len('canvas_width',   dims.total_width))
    lines.push(len('canvas_height',  dims.total_height))
    lines.push(len('bleed',          dims.bleed))
    lines.push(len('trim_width',     dims.trim_width))
    lines.push(len('trim_height',    dims.trim_height))
    lines.push(len('spine_width',    dims.spine_width))
    lines.push(len('back_x',         dims.back_x))
    lines.push(len('spine_x',        dims.spine_x))
    lines.push(len('front_x',        dims.front_x))
    lines.push(bool('has_spine',     dims.has_spine))
    lines.push(bool('has_bleed',     dims.has_bleed))
    lines.push('')

    // Text content
    lines.push('// Text content')
    lines.push(str('title',          schema.text.title))
    lines.push(str('title_pre',      schema.text.title_pre  ?? ''))
    lines.push(str('title_post',     schema.text.title_post ?? ''))
    lines.push(str('subtitle',       schema.text.subtitle   ?? ''))
    lines.push(str('author',         schema.text.author     ?? ''))
    lines.push(str('isbn',           schema.text.isbn       ?? ''))
    lines.push(content('back_blurb', schema.text.back_blurb))
    lines.push(bool('has_title_pre',  !!(schema.text.title_pre)))
    lines.push(bool('has_title_post', !!(schema.text.title_post)))
    lines.push(bool('has_subtitle',   !!(schema.text.subtitle)))
    lines.push(bool('has_author',     !!(schema.text.author)))
    lines.push(bool('has_isbn',       !!(schema.text.isbn)))
    lines.push('')

    // Colors
    lines.push('// Colors')
    lines.push(color('color_front_bg',       colors.front_background))
    lines.push(color('color_back_bg',        colors.back_background))
    lines.push(color('color_spine_bg',       colors.spine_background))
    lines.push(color('color_front_title',    colors.front_title))
    lines.push(color('color_front_title_pre',  colors.front_title_pre))
    lines.push(color('color_front_title_post', colors.front_title_post))
    lines.push(color('color_front_subtitle', colors.front_subtitle))
    lines.push(color('color_front_author',   colors.front_author))
    lines.push(color('color_back_blurb',     colors.back_blurb))
    lines.push(color('color_spine_title',    colors.spine_title))
    lines.push(color('color_spine_author',   colors.spine_author))
    lines.push(color('color_accent',         colors.accent))
    lines.push('')

    // Typography
    lines.push('// Typography')
    lines.push(str('font_family',    font_family))
    lines.push(ptval('fs_title',         font_sizes.title))
    lines.push(ptval('fs_title_pre',     font_sizes.title_pre))
    lines.push(ptval('fs_title_post',    font_sizes.title_post))
    lines.push(ptval('fs_subtitle',      font_sizes.subtitle))
    lines.push(ptval('fs_author',        font_sizes.author))
    lines.push(ptval('fs_back_blurb',    font_sizes.back_blurb))
    lines.push(ptval('fs_spine_title',   font_sizes.spine_title))
    lines.push(ptval('fs_spine_author',  font_sizes.spine_author))
    lines.push('')

    // Theme layout flags
    lines.push('// Theme layout')
    lines.push(bool('layout_uses_image',      layout.uses_image))
    lines.push(str('layout_image_style',      layout.image_style))
    lines.push(str('layout_title_valign',     layout.title_valign))
    lines.push(bool('layout_title_band',      layout.title_band))
    lines.push(bool('layout_inset_border',    layout.inset_border))
    lines.push(bool('layout_author_accent',   layout.author_accent))
    lines.push(bool('layout_accent_band',     layout.accent_band))
    lines.push(bool('layout_author_small_caps', layout.author_small_caps))
    lines.push('')

    // Image and barcode
    lines.push('// Assets')
    lines.push(bool('has_image',       image_filename !== null))
    lines.push(str('image_filename',   image_filename ?? ''))
    lines.push(bool('has_barcode',     has_barcode))
    lines.push('')

    return lines.join('\n')
}
